[WIP] SpaceTimeStack export data into JSON format
kokkos/kokkos-tools pull request #114
Opened 2020-11-30 13:52 UTC by dalg24

@pgrete

2021-02-03 15:22 UTC, DavidPoliakoff requested changes
Otherwise looks good

2021-02-03 15:22 UTC, DavidPoliakoff commented on profiling/space-time-stack/kp_space_time_stack.cpp
> +        stack_root.print_json(fout);
```suggestion
#if USE_MPI
      if (rank == 0) {
#endif
        std::ofstream fout("noname.json");
        stack_root.print_json(fout);
 #if USE_MPI
    }
 #endif
```

2021-02-03 15:38 UTC, DavidPoliakoff commented
Actually, another bug with ExaMiniMD:

```
  120 {
  121 "average-time" : 4.38e-03,
  122 "percent" : 0.1,
  123 "percent-kokkos" : 199.5,
  124 "imbalance" : 0.0,
  125 "remainder" : "N/A",
  126 "kernels-per-second" : "N/A",
  127 "number-of-calls" : 39,
>>128 "name" : ""CommMPI::pack_count"="Scalar"",
  129 "parent-id" : "0xe4a370",
  130 "id" : "0xe4a410",
  131 "kernel-type" : "copy"
  132 },
```
Apparently something in how this string is quoted is breaking... all the joys of I/O libraries ;)

2021-02-03 15:45 UTC, nmhamster commented
FYI - JSON double quotation marks inside a string must be escaped with ```\"```

2021-02-03 15:52 UTC, DavidPoliakoff commented
@nmhamster : are you still allowed to do technical work? :p

2021-02-04 23:12 UTC, dalg24 commented
Fixed the double quote bug

2021-02-05 19:47 UTC, DavidPoliakoff commented
@dalg24, I think my suggestion was broken in how it got applied, could you check that 
c24900a does what you want?

2021-02-10 17:08 UTC, dalg24 commented
> @dalg24, I think my suggestion was broken in how it got applied, could you check that
> [c24900a](https://github.com/kokkos/kokkos-tools/commit/c24900a194db223db62830296a9001f341c78a86) does what you want?

It does

2021-02-10 17:27 UTC, DavidPoliakoff approved these changes

2021-02-10 17:28 UTC, merged