Allow HIP and SYCL in space-time-stack
kokkos/kokkos-tools pull request #119
Opened 2021-04-12 14:20 UTC by masterleinad

With this patch information for allocations in `Host`, `Cuda`, `HIP`, and `SYCL` memory spaces are recorded in `space-time-stack`.

2021-04-12 14:51 UTC, dalg24 approved these changes
I would use `strncmp` but not blocking

2021-04-12 14:51 UTC, dalg24 commented on profiling/space-time-stack/kp_space_time_stack.cpp
> +      strcmp(handle.name, "CudaHostPinned")==0 )
```suggestion
  if (strncmp(handle.name, "Cuda", 4) == 0)  // check that name starts with "Cuda"
```

2021-04-16 16:25 UTC, DavidPoliakoff requested changes
Agree with Damien's comment, but I'll block on it. This way if we do something weird to the Cuda backend, we still should see this work

2021-04-16 16:50 UTC, masterleinad commented on profiling/space-time-stack/kp_space_time_stack.cpp
> +      strcmp(handle.name, "CudaHostPinned")==0 )
Changed for `CUDA`, `HIP` and `SYCL`.

2021-05-18 17:57 UTC, masterleinad commented
@DavidPoliakoff Is there anything else you want me to do here?

2021-05-25 20:05 UTC, DavidPoliakoff approved these changes

2021-05-25 20:06 UTC, DavidPoliakoff commented
@masterleinad: in the long term, we're phasing out develop, but for the moment could you retarget against develop?

2021-05-25 20:11 UTC, masterleinad commented
Sure, targeting `develop` now.

2021-06-25 16:56 UTC, DavidPoliakoff commented
I don't know how I forgot to merge this, apologies

2021-06-25 16:57 UTC, merged